databases:
  - name: cardapio-digital-db
    plan: free

services:
  - type: web
    name: cardapio-digital
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: >-
      bash -c "./bin/rails db:prepare &&
      (./bin/rails runner \"exit 1 unless ActiveRecord::Base.connection.table_exists?('users')\" || ./bin/rails db:schema:load) &&
      ./bin/rails db:seed &&
      ./bin/rails server"
    plan: free
    healthCheckPath: /up
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: cardapio-digital-db
          property: connectionString
